# -*- coding: utf-8 -*-
"""python_internal1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16KrZ2dHVKDOC8lch4975sB6oQ9F3NXMb
"""

# ques1
length = float(input('Enter the length: '))
width = float(input('Enter the width: '))
area = length * width
print(f'The area of rectangle is {area}')

#ques2
 weight = float(input('Enter the weight: '))
 height = float(input('Enter the height: '))
 height = height/100
 bmi = weight/(height**2)
 print(f'The bmi value is {bmi:.2f}')

#ques3
details = {}
n = int(input('Enter the num of students:'))
for i in range(n):
  name = input('Enter your name:')
  score = input('enter your score: ')
  details[name] = score
print('---Student_name , score--')
#print(details)
for key,val in details.items():
  print(key,val)

#ques4
name = input('Enter your name- ')
age = int(input('Enter your age: '))
if age<18:
  print(f'Hii {name},Your minor.')
elif age>45:
  print(f'Hii {name},Your senior person')
else:
  print(f'Hii {name}, Your an adult')

#ques5
print('Even numbers')
for i in range(1,51):
  if i%2 == 0:
    print(i , end=" ")

#ques6
password = input('Create a password: ')
flag = True
while flag:
  print('Login')
  enter_pass = input('Enter your password:')
  if password == enter_pass:
    flag = False
    break
  else:
    print('Password incorrect')
print('You have entered correct password')

#ques7
def average_of_list(num):
    if len(num) == 0:
        return None
    else:
        total = sum(num)
        average = total / len(num)
        return average

num = [10, 20, 30, 40, 50]
avg = average_of_list(num)
print("Average:", avg)

#ques8
def count(s):
  count = 0
  for char in s:
    if char in ['a','e','i','o','u']:
      count +=1
  return count



string = input('Enter the string : ')
result = count(string)
print(result)

#ques9
from datetime import datetime
current_date =datetime.now()
print(current_date)

#ques10
try:
  a = 1
  b = '2'
  sum = a+b
  print(sum)
except:
  print('Enter correct input ')

#ques11
while True:
    try:
        user_input = int(input("Please enter an integer: "))
        break
    except ValueError:
        print("Invalid input.Value is not in the given datatype.")

print( user_input)

#ques12

try:
  a=int(input('Enter a: '))
  b=int(input('Enter b: '))
  result = a/b
  print(result)
except ZeroDivisionError:
  print('denominator cannot be zero')

#ques13
data = 'Hello, Python!'
with open('file.txt','w') as file:
  file.write(data)


print("Successfully wrote 'Hello, Python!' to file.txt")

#ques14
with open('file.txt','r') as file:
  content = file.read()
  print(content)

#ques15
data = "This is a new line."

with open("file.txt", "a") as file:
    file.write("\n" + data)
with open("file.txt", "r") as file:
    new_file = file.read()

print(new_file)